added browser extension link and new menu in receive tab.
ethereum-push-notification-service/epns-dapp-staging pull request #22
Opened 2021-12-18 07:13 UTC by rijusougata13

2021-12-18 07:15 UTC, rijusougata13 commented
Also fixed undefined url when click on ios and android. PTAL @zaryab2000

2021-12-20 07:39 UTC, zaryab2000 commented
Looks good to me @rijusougata13 .

Added @Xand6r as a reviewer for a quick review and then we can merge

2021-12-20 11:24 UTC, Xand6r requested changes

2021-12-20 11:24 UTC, Xand6r commented on packages/react-app/src/components/ViewInfoItem.js
>    // render
perhaps we could do :
```
const { REACT_APP_BROWSER_EXTENSION_URL } = process.env;
```
here

2021-12-20 11:24 UTC, Xand6r commented on packages/react-app/src/components/ViewInfoItem.js
> +            <AppLink href={`${process.env.REACT_APP_BROWSER_EXTENSION_URL}`} target="_blank" rel="nofollow">
then :
```
<AppLink href={REACT_APP_BROWSER_EXTENSION_URL} target="_blank" rel="nofollow">
```
here.

2021-12-20 14:53 UTC, merged